package Tampilan;
import Koneksi.Koneksi;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Lenovo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
jMenuBar1.setPreferredSize(new java.awt.Dimension(0, 50));
jMenu1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 20));
jMenu2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 20));
jMenu3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 20));
jMenu5.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 20));
       getContentPane().setLayout(new java.awt.BorderLayout());
    getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LOGOUT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        DataB = new javax.swing.JMenuItem();
        DataK = new javax.swing.JMenuItem();
        DataP = new javax.swing.JMenuItem();
        DataS = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Pemesanan = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        LDB = new javax.swing.JMenuItem();
        LDK = new javax.swing.JMenuItem();
        LDP = new javax.swing.JMenuItem();
        LDS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(300, 32769));

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("File");

        LOGOUT.setText("LogOut");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        jMenu1.add(LOGOUT);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Data");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        DataB.setText("Data Barang");
        DataB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBActionPerformed(evt);
            }
        });
        jMenu2.add(DataB);

        DataK.setText("Data Karyawan");
        DataK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataKActionPerformed(evt);
            }
        });
        jMenu2.add(DataK);

        DataP.setText("Data Pelanggan");
        DataP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPActionPerformed(evt);
            }
        });
        jMenu2.add(DataP);

        DataS.setText("Data Suplier");
        DataS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataSActionPerformed(evt);
            }
        });
        jMenu2.add(DataS);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        Pemesanan.setText("Transaksi Pemesanan");
        Pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemesananActionPerformed(evt);
            }
        });
        jMenu3.add(Pemesanan);

        jMenuItem5.setText("Transaksi Pembayaran");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setText("Laporan");

        LDB.setText("Laporan Data Barang");
        LDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDBActionPerformed(evt);
            }
        });
        jMenu5.add(LDB);

        LDK.setText("Laporan Data Karyawan");
        LDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDKActionPerformed(evt);
            }
        });
        jMenu5.add(LDK);

        LDP.setText("Laporan Data Pembayaran");
        LDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDPActionPerformed(evt);
            }
        });
        jMenu5.add(LDP);

        LDS.setText("Laporan Data Suplier");
        LDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDSActionPerformed(evt);
            }
        });
        jMenu5.add(LDS);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            // buka form login
            Login login = new Login();
            login.setVisible(true);

            // tutup form menu
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void DataBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBActionPerformed
        DataBarang form = new DataBarang();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true);  
        // TODO add your handling code here:
    }//GEN-LAST:event_DataBActionPerformed

    private void DataKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataKActionPerformed
        DataKaryawan form = new DataKaryawan();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_DataKActionPerformed

    private void DataPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPActionPerformed
        DataPelanggan form = new DataPelanggan();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_DataPActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void LDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDBActionPerformed
        LaporanDataBarang form = new LaporanDataBarang();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_LDBActionPerformed

    private void LDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDKActionPerformed
       LaporanDataKaryawan form = new LaporanDataKaryawan();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_LDKActionPerformed

    private void LDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDPActionPerformed
LaporanDataPembayaran form = new LaporanDataPembayaran();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LDPActionPerformed

    private void DataSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataSActionPerformed
      DataSupplier form = new DataSupplier();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_DataSActionPerformed

    private void LDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDSActionPerformed
       LaporanDataSupplier form = new LaporanDataSupplier();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_LDSActionPerformed

    private void PemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemesananActionPerformed
 TransaksiPemesanan form = new TransaksiPemesanan();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_PemesananActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       TransaksiPembayaran form = new TransaksiPembayaran();
        jDesktopPane1.add(form); // ✅ pakai nama yang benar
        form.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DataB;
    private javax.swing.JMenuItem DataK;
    private javax.swing.JMenuItem DataP;
    private javax.swing.JMenuItem DataS;
    private javax.swing.JMenuItem LDB;
    private javax.swing.JMenuItem LDK;
    private javax.swing.JMenuItem LDP;
    private javax.swing.JMenuItem LDS;
    private javax.swing.JMenuItem LOGOUT;
    private javax.swing.JMenuItem Pemesanan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
