/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;
import javax.swing.SpinnerDateModel;
import javax.swing.JSpinner;
import java.text.SimpleDateFormat;
/**
 *
 * @author ADVAN
 */
public class TransaksiPemesanan extends javax.swing.JInternalFrame {
 private Statement St;
private Connection Con;
private ResultSet Rs;
private String sql="";
    /**
     * Creates new form TransaksiPemesanan
     */
    public TransaksiPemesanan() {
        initComponents();
        setClosable(true);
        setMaximizable(false);
        setIconifiable(true); 
        setResizable(true);
        
    setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
    setTitle("Transaksi Pemesanan");
    SpinnerDateModel model = new SpinnerDateModel();
    model.setCalendarField(Calendar.HOUR_OF_DAY);

    JAM.setModel(model);
    JSpinner.DateEditor editor = new JSpinner.DateEditor(JAM, "HH:mm:ss");
    JAM.setEditor(editor);
    JAM.setValue(new java.util.Date());
    
    autonumber();
    tampilData();
    
    NT.setEditable(false);
    KP.setEditable(false);     
    NamaPM.setEditable(false);    
    KBP.setEditable(false);    
    JBP.setEditable(false);    
    
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    
    //TAMPILKAN DATA KE JTABLE
private void tampilData() {

    DefaultTableModel model = new DefaultTableModel(
        new Object[][]{},
        new String[]{
    "No Transaksi",
    "Tanggal",
    "Jam",
    "Nama",
    "Kode Barang",
    "Kode Pemesanan",
    "Jenis Barang",
    "Harga Satuan",
    "Jumlah",
    "Total"
}
        
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    try {
        Connection con = Koneksi.getConnection();
        Statement st = con.createStatement();

        String sql = "SELECT t.NoTransaksi, t.Tanggal, t.Jam, "
                + "t.KodePesanan, p.NamaP, "
                + "t.KodeBR, b.JenisB, "
                + "t.Jumlah, b.Harga, t.Total "
                + "FROM transaksipemesanan t "
                + "JOIN pelanggan p ON t.KodePesanan = p.KodeP "
                + "JOIN databarang b ON t.KodeBR = b.KodeB";

        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("NoTransaksi"),
                rs.getString("Tanggal"),
                rs.getString("Jam"),
                rs.getString("NamaP"),
                rs.getString("KodeBR"),
                rs.getString("KodePesanan"),
                rs.getString("JenisB"),
                rs.getInt("Harga"),
                rs.getInt("Jumlah"),
                rs.getInt("Total")
            });
        }

        tbl.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
    }
}


//AUTO GENERATE KODE
private void autonumber() {
    try {
        Connection con = Koneksi.getConnection();

        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(
            "SELECT NoTransaksi FROM transaksipemesanan ORDER BY NoTransaksi DESC LIMIT 1"
        );

        if (rs.next()) {

            String kode = rs.getString(1).trim(); // penting: trim biar tidak error

            // ambil angka setelah huruf T
            String angka = kode.replaceAll("[^0-9]", "");

            int nomor = Integer.parseInt(angka);

            nomor++;

            NT.setText(String.format("T%02d", nomor));

        } else {
            NT.setText("T01");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nt = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Tgl = new javax.swing.JLabel();
        Nma = new javax.swing.JLabel();
        NT = new javax.swing.JTextField();
        NamaPM = new javax.swing.JTextField();
        cariKP = new javax.swing.JButton();
        jm = new javax.swing.JLabel();
        kb = new javax.swing.JLabel();
        kp = new javax.swing.JLabel();
        jb = new javax.swing.JLabel();
        hrga = new javax.swing.JLabel();
        jml = new javax.swing.JLabel();
        ttl = new javax.swing.JLabel();
        KBP = new javax.swing.JTextField();
        KP = new javax.swing.JTextField();
        JBP = new javax.swing.JTextField();
        HS = new javax.swing.JTextField();
        JMLP = new javax.swing.JTextField();
        TOTALP = new javax.swing.JTextField();
        cariKB = new javax.swing.JButton();
        smpn = new javax.swing.JButton();
        edt = new javax.swing.JButton();
        hps = new javax.swing.JButton();
        rd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        TGL = new de.wannawork.jcalendar.JCalendarComboBox();
        edt1 = new javax.swing.JButton();
        JAM = new javax.swing.JSpinner();
        Batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nt.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRANSAKSI PEMESANAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        jLabel1.setText("No Transaksi");

        Tgl.setText("Tanggal");

        Nma.setText("Nama");

        NT.setText(" ");
        NT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NTActionPerformed(evt);
            }
        });

        NamaPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPMActionPerformed(evt);
            }
        });

        cariKP.setText("Cari");
        cariKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariKPActionPerformed(evt);
            }
        });

        jm.setText("Jam");

        kb.setText("Kode Barang");

        kp.setText("Kode Pesanan");

        jb.setText("Jenis Barang");

        hrga.setText("Harga Satuan");

        jml.setText("Jumlah");

        ttl.setText("Total");

        KBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KBPActionPerformed(evt);
            }
        });

        KP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KPActionPerformed(evt);
            }
        });

        JBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPActionPerformed(evt);
            }
        });

        HS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSActionPerformed(evt);
            }
        });

        JMLP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JMLPKeyPressed(evt);
            }
        });

        TOTALP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALPActionPerformed(evt);
            }
        });

        cariKB.setText("Cari");
        cariKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariKBActionPerformed(evt);
            }
        });

        smpn.setText("SIMPAN");
        smpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpnActionPerformed(evt);
            }
        });

        edt.setText("EDIT");
        edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtActionPerformed(evt);
            }
        });

        hps.setText("HAPUS");
        hps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpsActionPerformed(evt);
            }
        });

        rd.setText("Refresh Data");
        rd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Tanggal", "Jam", "Nama", "Kode Barang", "Kode Pemesanan", "Jenis Barang", "Harga Satuan", "Jumlah", "Total"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        edt1.setText("Hitung");
        edt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt1ActionPerformed(evt);
            }
        });

        Batal.setText("Batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NtLayout = new javax.swing.GroupLayout(Nt);
        Nt.setLayout(NtLayout);
        NtLayout.setHorizontalGroup(
            NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(NtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NtLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(NtLayout.createSequentialGroup()
                        .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NtLayout.createSequentialGroup()
                                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nma, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jm)
                                    .addComponent(kp)
                                    .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(NtLayout.createSequentialGroup()
                                        .addComponent(KP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cariKP))
                                    .addGroup(NtLayout.createSequentialGroup()
                                        .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NT, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TGL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(142, 142, 142)
                                        .addComponent(kb))
                                    .addGroup(NtLayout.createSequentialGroup()
                                        .addGap(288, 288, 288)
                                        .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(NtLayout.createSequentialGroup()
                                        .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NamaPM, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JAM, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(KBP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(NtLayout.createSequentialGroup()
                                                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(hrga)
                                                    .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(edt1))
                                                .addGap(65, 65, 65)
                                                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TOTALP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JMLP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(HS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JBP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addComponent(cariKB))))
                            .addGroup(NtLayout.createSequentialGroup()
                                .addComponent(smpn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edt)
                                .addGap(9, 9, 9)
                                .addComponent(hps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rd))
                        .addContainerGap())))
        );
        NtLayout.setVerticalGroup(
            NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NtLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kb)
                    .addComponent(KBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariKB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tgl)
                    .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jm))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hrga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kp)
                    .addComponent(KP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariKP)
                    .addComponent(jml)
                    .addComponent(JMLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TOTALP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nma)
                        .addComponent(NamaPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ttl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt1)
                .addGap(31, 31, 31)
                .addGroup(NtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smpn)
                    .addComponent(edt)
                    .addComponent(hps)
                    .addComponent(Batal))
                .addGap(65, 65, 65)
                .addComponent(rd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        getContentPane().add(Nt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 955));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KPActionPerformed

    private void KBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KBPActionPerformed

    private void NamaPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPMActionPerformed

    private void cariKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariKPActionPerformed
String input = JOptionPane.showInputDialog(
        null,
        "Masukkan Kode Pelanggan (tanpa KP):",
        "Cari Data",
        JOptionPane.QUESTION_MESSAGE
);

if (input == null || input.trim().isEmpty()) {
    return;
}

String kode = "KP" + input;

    if (kode == null || kode.trim().isEmpty()) {
        return;
    }

    try {
        Connection con = Koneksi.getConnection();

        String sql = "SELECT NamaP FROM pelanggan WHERE KodeP = ?";
        PreparedStatement St = con.prepareStatement(sql);
        St.setString(1, kode);

        ResultSet Rs = St.executeQuery();

        if (Rs.next()) {
            KP.setText(kode);
            NamaPM.setText(Rs.getString("NamaP"));
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
           NamaPM.setText("");
        }

        Rs.close();
        St.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_cariKPActionPerformed

    private void rdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdActionPerformed
tampilData();        // TODO add your handling code here:
    }//GEN-LAST:event_rdActionPerformed

    private void NTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NTActionPerformed

    private void TOTALPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTALPActionPerformed

    private void edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtActionPerformed
try {
        Connection con = Koneksi.getConnection();

      String sql = "UPDATE transaksipemesanan "
           + "SET Tanggal=?, KodeBR=?, Jumlah=?, Total=? "
           + "WHERE NoTransaksi=?";

        PreparedStatement pst = con.prepareStatement(sql);

        java.util.Date tgl = TGL.getDate();
        java.sql.Date sqlTanggal = new java.sql.Date(tgl.getTime());

      pst.setDate(1, sqlTanggal);
pst.setString(2, KBP.getText()); // Kode Barang
pst.setInt(3, Integer.parseInt(JMLP.getText()));
pst.setDouble(4, Double.parseDouble(TOTALP.getText()));
pst.setString(5, NT.getText());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null,
                "Data berhasil diubah");

        tampilData();
        autonumber();
        KP.setText("");
        NamaPM.setText("");
        KBP.setText("");
        JBP.setText("");
        HS.setText("");
        JMLP.setText("");
        TOTALP.setText("");

        TGL.setDate(new java.util.Date());
        JAM.setValue(new java.util.Date());

    tbl.clearSelection();

NT.requestFocus();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
                "Gagal mengubah data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_edtActionPerformed

    private void edt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt1ActionPerformed
     
        try {
        int jumlah = Integer.parseInt(JMLP.getText());
        int harga = Integer.parseInt(HS.getText());

        int total = jumlah * harga;

        TOTALP.setText(String.valueOf(total));

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Input jumlah atau harga harus angka!");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_edt1ActionPerformed

    private void HSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HSActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed

    NT.setText("");
    KP.setText("");
    NamaPM.setText("");
    KBP.setText("");
    JBP.setText("");
    HS.setText("");
    JMLP.setText("");
    TOTALP.setText("");

    TGL.setDate(new java.util.Date());

    // reset jam ke waktu sekarang
    JAM.setValue(new java.util.Date());
    autonumber();
    // hilangkan pilihan pada JTable
    tbl.clearSelection();

    NT.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_BatalActionPerformed

    private void cariKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariKBActionPerformed
 String input = JOptionPane.showInputDialog(
        null,
        "Masukkan Kode Barang (tanpa KB):",
        "Cari Data",
        JOptionPane.QUESTION_MESSAGE
);

if (input == null || input.trim().isEmpty()) {
    return;
}

String kode = "KB" + input;

try {
    Connection con = Koneksi.getConnection();

    String sql = "SELECT JenisB, Harga FROM databarang WHERE KodeB = ?";
    PreparedStatement St = con.prepareStatement(sql);
    St.setString(1, kode);

    ResultSet Rs = St.executeQuery();

    if (Rs.next()) {
        KBP.setText(kode);
        JBP.setText(Rs.getString("JenisB"));
        HS.setText(Rs.getString("Harga")); 
    } else {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        JBP.setText("");
        HS.setText("");
    }

    Rs.close();
    St.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}     // TODO add your handling code here:
    }//GEN-LAST:event_cariKBActionPerformed

    private void smpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpnActionPerformed
try {
        Connection con = Koneksi.getConnection();

        String sql = "INSERT INTO transaksipemesanan "
                + "(NoTransaksi, Tanggal, Jam, KodePesanan, KodeBR, Jumlah, Total) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = con.prepareStatement(sql);

        // tanggal dari JDateChooser
        java.util.Date tgl = TGL.getDate();
        java.sql.Date sqlTanggal = new java.sql.Date(tgl.getTime());

        // jam dari spinner
       SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
String jam = sdf.format(JAM.getValue());

        pst.setString(1, NT.getText());
        pst.setDate(2, sqlTanggal);
        pst.setString(3, jam);
        pst.setString(4, KP.getText()); // KodePL
        pst.setString(5, KBP.getText());    // KodeBR
        pst.setInt(6, Integer.parseInt(JMLP.getText()));
        pst.setInt(7, Integer.parseInt(TOTALP.getText()));

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");

        pst.close();
        autonumber();
        // refresh tabel
        tampilData();
        
        
        // KOSONGKAN FORM
        NamaPM.setText("");
        JBP.setText("");
        HS.setText("");
        KP.setText("");
        KBP.setText("");
        JMLP.setText("");
        TOTALP.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal simpan: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_smpnActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
 int baris = tbl.getSelectedRow();

    NT.setText(tbl.getValueAt(baris, 0).toString());
    TGL.setDate(java.sql.Date.valueOf(tbl.getValueAt(baris, 1).toString()));

    NamaPM.setText(tbl.getValueAt(baris, 3).toString());
    KBP.setText(tbl.getValueAt(baris, 4).toString());
    KP.setText(tbl.getValueAt(baris, 5).toString());
    JBP.setText(tbl.getValueAt(baris, 6).toString());

    HS.setText(tbl.getValueAt(baris, 7).toString());
    JMLP.setText(tbl.getValueAt(baris, 8).toString());
    TOTALP.setText(tbl.getValueAt(baris, 9).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void hpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpsActionPerformed
int konfirmasi = JOptionPane.showConfirmDialog(
            null,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {

        try {
            Connection con = Koneksi.getConnection();

            String sql = "DELETE FROM transaksipemesanan WHERE NoTransaksi=?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, NT.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

            // Kosongkan form
            NT.setText("");
            KP.setText("");
            NamaPM.setText("");
            KBP.setText("");
            JBP.setText("");
            HS.setText("");
            JMLP.setText("");
            TOTALP.setText("");
            TGL.setDate(null);

            // Hapus baris dari JTable
            int baris = tbl.getSelectedRow();
            if (baris != -1) {
                ((DefaultTableModel) tbl.getModel()).removeRow(baris);
            }
            autonumber();
            tampilData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Gagal menghapus data: " + e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_hpsActionPerformed

    private void JBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBPActionPerformed

    private void JMLPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JMLPKeyPressed
if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {

        try {
            int jumlah = Integer.parseInt(JMLP.getText());
            int harga = Integer.parseInt(HS.getText());

            int total = jumlah * harga;

            TOTALP.setText(String.valueOf(total));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Jumlah atau Harga tidak valid!");
        }

    }        // TODO add your handling code here:
    }//GEN-LAST:event_JMLPKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JTextField HS;
    private javax.swing.JSpinner JAM;
    private javax.swing.JTextField JBP;
    private javax.swing.JTextField JMLP;
    private javax.swing.JTextField KBP;
    private javax.swing.JTextField KP;
    private javax.swing.JTextField NT;
    private javax.swing.JTextField NamaPM;
    private javax.swing.JLabel Nma;
    private javax.swing.JPanel Nt;
    private de.wannawork.jcalendar.JCalendarComboBox TGL;
    private javax.swing.JTextField TOTALP;
    private javax.swing.JLabel Tgl;
    private javax.swing.JButton cariKB;
    private javax.swing.JButton cariKP;
    private javax.swing.JButton edt;
    private javax.swing.JButton edt1;
    private javax.swing.JButton hps;
    private javax.swing.JLabel hrga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jb;
    private javax.swing.JLabel jm;
    private javax.swing.JLabel jml;
    private javax.swing.JLabel kb;
    private javax.swing.JLabel kp;
    private javax.swing.JButton rd;
    private javax.swing.JButton smpn;
    private javax.swing.JTable tbl;
    private javax.swing.JLabel ttl;
    // End of variables declaration//GEN-END:variables
}
